//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiMenuMapping
    {
        public string ApiIDSys { get; set; }
        public int MenuIDSys { get; set; }
        public bool GET { get; set; }
        public bool POST { get; set; }
        public bool PUT { get; set; }
        public bool DEL { get; set; }
        public string Type { get; set; }
    
        public virtual Api_MT Api_MT { get; set; }
        public virtual Menu_MT Menu_MT { get; set; }
    }
}
