//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyUnit
    {
        public int CurrencyIDSys { get; set; }
        public string CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public string Country { get; set; }
        public byte Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UserUpdate { get; set; }
    }
}
