//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_MT
    {
        public string EmID { get; set; }
        public int PersonIDSys { get; set; }
        public string Area { get; set; }
        public string Position { get; set; }
        public string Dept { get; set; }
        public string TelOffice { get; set; }
        public string TelEx { get; set; }
        public byte Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<System.DateTime> HiredDate { get; set; }
        public Nullable<int> PositionIDSys { get; set; }
    
        public virtual Person_MT Person_MT { get; set; }
    }
}
