//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDefinitionDetail_MT
    {
        public int ImportIDSys { get; set; }
        public string ColumnName { get; set; }
        public string Mandatory { get; set; }
        public string FixedValue { get; set; }
        public string Import { get; set; }
        public int Digits { get; set; }
        public string DataType { get; set; }
    
        public virtual ImportDefinitionHeader_MT ImportDefinitionHeader_MT { get; set; }
    }
}
