//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDefinitionHeader_MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportDefinitionHeader_MT()
        {
            this.ImportDefinitionDetail_MT = new HashSet<ImportDefinitionDetail_MT>();
        }
    
        public int ImportIDSys { get; set; }
        public string ImportID { get; set; }
        public string ForTable { get; set; }
        public string FormatName { get; set; }
        public string Delimiter { get; set; }
        public Nullable<int> MaxHeading { get; set; }
        public string Encoding { get; set; }
        public Nullable<bool> SkipFirstRecode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportDefinitionDetail_MT> ImportDefinitionDetail_MT { get; set; }
    }
}
