//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSetDetail
    {
        public int IDSys { get; set; }
        public int ItemSetIDSys { get; set; }
        public int ItemIDSys { get; set; }
        public int Qty { get; set; }
    
        public virtual Item_MT Item_MT { get; set; }
        public virtual ItemSet_MT ItemSet_MT { get; set; }
    }
}
