//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInspectMapping
    {
        public int ItemInspectIDSys { get; set; }
        public int ItemIDSys { get; set; }
        public int InspectIDSys { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UserUpdate { get; set; }
    
        public virtual Inspect_MT Inspect_MT { get; set; }
        public virtual Item_MT Item_MT { get; set; }
    }
}
