//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemUnitMapping
    {
        public int ItemIDSys { get; set; }
        public int UnitIDSys { get; set; }
        public float Weight { get; set; }
        public float Width { get; set; }
        public float Length { get; set; }
        public float Height { get; set; }
        public byte MainUnit { get; set; }
        public byte Sequence { get; set; }
        public short QtyInParent { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Item_MT Item_MT { get; set; }
        public virtual Unit_MT Unit_MT { get; set; }
    }
}
