//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelLayoutHeader_MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabelLayoutHeader_MT()
        {
            this.LabelLayoutDetail_MT = new HashSet<LabelLayoutDetail_MT>();
        }
    
        public int LabelIDSys { get; set; }
        public string LabelID { get; set; }
        public string FormatName { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string WidthUnit { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string HeightUnit { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserUpdate { get; set; }
        public string ForTable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelLayoutDetail_MT> LabelLayoutDetail_MT { get; set; }
    }
}
