//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_MT
    {
        public int LocIDSys { get; set; }
        public string LineID { get; set; }
        public string WHID { get; set; }
        public string LocNo { get; set; }
        public string QualityType { get; set; }
        public string RackType { get; set; }
        public string Tempature { get; set; }
        public float Weight { get; set; }
        public float Width { get; set; }
        public float Length { get; set; }
        public float Height { get; set; }
        public byte Active { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UserUpdate { get; set; }
        public int CateIDSys { get; set; }
    
        public virtual Category_MT Category_MT { get; set; }
    }
}
