//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_MT()
        {
            this.MenuProjectMappings = new HashSet<MenuProjectMapping>();
            this.ApiMenuMappings = new HashSet<ApiMenuMapping>();
        }
    
        public int MenuIDSys { get; set; }
        public int MenuParentID { get; set; }
        public string MenuName { get; set; }
        public string Url { get; set; }
        public string Api { get; set; }
        public Nullable<byte> Sort { get; set; }
        public string MenuPic { get; set; }
        public Nullable<byte> MenuProgramID { get; set; }
        public Nullable<byte> Header { get; set; }
        public Nullable<int> MenuGroupID { get; set; }
        public Nullable<int> AjaxMenu { get; set; }
        public Nullable<int> ProjectIDSys { get; set; }
        public Nullable<byte> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuProjectMapping> MenuProjectMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiMenuMapping> ApiMenuMappings { get; set; }
    }
}
