//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuProjectMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuProjectMapping()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int MenuIDSys { get; set; }
        public int ProjectIDSys { get; set; }
        public byte Sort { get; set; }
        public string MenuName { get; set; }
        public byte[] MenuPic { get; set; }
        public int MenuIDSysParent { get; set; }
    
        public virtual Menu_MT Menu_MT { get; set; }
        public virtual Project_MT Project_MT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
