//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportLayoutHeader_MT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportLayoutHeader_MT()
        {
            this.ReportLayoutDetail_MT = new HashSet<ReportLayoutDetail_MT>();
        }
    
        public int ReportIDSys { get; set; }
        public string ReportID { get; set; }
        public string FormatName { get; set; }
        public string FormatType { get; set; }
        public string FileExtention { get; set; }
        public string Delimiter { get; set; }
        public string TextGualifier { get; set; }
        public string Encoding { get; set; }
        public Nullable<int> StartExportRow { get; set; }
        public Nullable<bool> IncludeHeader { get; set; }
        public Nullable<bool> AddHeaderLayout { get; set; }
        public string HeaderLayout { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserUpdate { get; set; }
        public string ForTable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportLayoutDetail_MT> ReportLayoutDetail_MT { get; set; }
    }
}
