//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Master
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProjectMapping
    {
        public string UserID { get; set; }
        public int ProjectIDSys { get; set; }
    
        public virtual Project_MT Project_MT { get; set; }
        public virtual User User { get; set; }
    }
}
