//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuji.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportSerialDetail
    {
        public string DetailID { get; set; }
        public string HeadID { get; set; }
        public string ItemCode { get; set; }
        public string SerialNumber { get; set; }
        public string BoxNumber { get; set; }
        public string ItemGroup { get; set; }
        public string ItemType { get; set; }
        public string Status { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserUpdate { get; set; }
    
        public virtual ImportSerialHead ImportSerialHead { get; set; }
    }
}
