//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isuzu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundItemsHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InboundItemsHead()
        {
            this.InboundItems = new HashSet<InboundItems>();
        }
    
        public string InvNo { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsExport { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InboundItems> InboundItems { get; set; }
    }
}
