//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isuzu.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WIM_ISUZU_DEVntities : DbContext
    {
        public WIM_ISUZU_DEVntities()
            : base("name=WIM_ISUZU_DEVntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InboundItems> InboundItems { get; set; }
        public virtual DbSet<InboundItemsHead> InboundItemsHead { get; set; }
        public virtual DbSet<LabelRunning> LabelRunning { get; set; }
    
        public virtual ObjectResult<string> ProcGetNewID(string prefixes)
        {
            var prefixesParameter = prefixes != null ?
                new ObjectParameter("Prefixes", prefixes) :
                new ObjectParameter("Prefixes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ProcGetNewID", prefixesParameter);
        }
    
        public virtual int ProcPagingInboundItemGroups(Nullable<int> page, Nullable<int> size, ObjectParameter totalRecord)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcPagingInboundItemGroups", pageParameter, sizeParameter, totalRecord);
        }
    
        public virtual ObjectResult<ProcPagingInboundItemHead_Result> ProcPagingInboundItemHead(Nullable<int> page, Nullable<int> size, ObjectParameter totalRecord)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcPagingInboundItemHead_Result>("ProcPagingInboundItemHead", pageParameter, sizeParameter, totalRecord);
        }
    
        public virtual ObjectResult<ProcPagingInboundItems_Result> ProcPagingInboundItems(Nullable<int> page, Nullable<int> size, ObjectParameter totalRecord)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcPagingInboundItems_Result>("ProcPagingInboundItems", pageParameter, sizeParameter, totalRecord);
        }
    }
}
