//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isuzu.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelRunning
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Running { get; set; }
        public bool Printing { get; set; }
    }
}
